export const data = [
  {
    budget_cost_unit: '',
    budget_cost_value: '0',
    budget_fact_unit: '',
    budget_fact_value: '0',
    budget_plan_unit: '',
    budget_plan_value: '0',
    denotation: 'РСТ-2024',
    description: 'Описание проекта 1',
    filesfolder_name: null,
    goal: 'Цель проекта 1',
    guid: '3386feff-1b42-44a7-8345-6289eac1b20',
    id: '33',
    mainscheduledplan_actualdurationindays: '0',
    mainscheduledplan_actualenddate: null,
    mainscheduledplan_actualstartdate: '2024-01-20T09:00:00',
    mainscheduledplan_durationindays: '405',
    mainscheduledplan_enddate: '31.01.2027',
    mainscheduledplan_name: 'План проекта 1',
    mainscheduledplan_progress: '90 %',
    mainscheduledplan_projectelemanswerableuser_photo: null,
    mainscheduledplan_projectelemanswerableuser_shortname: 'Петров П.П.',
    mainscheduledplan_s_guid: '33d7059a-f54a-47e6-ab8b-1b4d8d995a60',
    mainscheduledplan_startdate: '01.08.2025',
    name: 'Проект 1: Разработка системы',
    number: 1,
    result: 'В процессе',
    s_classid: 'Портфель',
    type: 'Портфель',
  },
]
